[2022-11-27T18:45:31.510+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table manual__2022-11-27T18:45:29.807798+00:00 [queued]>
[2022-11-27T18:45:31.522+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table manual__2022-11-27T18:45:29.807798+00:00 [queued]>
[2022-11-27T18:45:31.523+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-27T18:45:31.523+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 6
[2022-11-27T18:45:31.523+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-27T18:45:31.542+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2022-11-27 18:45:29.807798+00:00
[2022-11-27T18:45:31.547+0000] {standard_task_runner.py:55} INFO - Started process 816 to run task
[2022-11-27T18:45:31.550+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v01', 'create_postgres_table', 'manual__2022-11-27T18:45:29.807798+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmp1oxj9hvn']
[2022-11-27T18:45:31.551+0000] {standard_task_runner.py:83} INFO - Job 97: Subtask create_postgres_table
[2022-11-27T18:45:31.609+0000] {task_command.py:376} INFO - Running <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table manual__2022-11-27T18:45:29.807798+00:00 [running]> on host 04d264156372
[2022-11-27T18:45:31.684+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Bruno Lima
AIRFLOW_CTX_DAG_ID=dag_with_postgres_operator_v01
AIRFLOW_CTX_TASK_ID=create_postgres_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-27T18:45:29.807798+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-27T18:45:29.807798+00:00
[2022-11-27T18:45:31.693+0000] {base.py:71} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-11-27T18:45:31.710+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 94, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 288, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 115, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "host.docker.internal" to address: Name or service not known

[2022-11-27T18:45:31.717+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v01, task_id=create_postgres_table, execution_date=20221127T184529, start_date=20221127T184531, end_date=20221127T184531
[2022-11-27T18:45:31.729+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 97 for task create_postgres_table (could not translate host name "host.docker.internal" to address: Name or service not known
; 816)
[2022-11-27T18:45:31.762+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-27T18:45:31.781+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
