[2022-11-30T01:32:34.865+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table scheduled__2022-11-29T00:00:00+00:00 [queued]>
[2022-11-30T01:32:34.979+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table scheduled__2022-11-29T00:00:00+00:00 [queued]>
[2022-11-30T01:32:34.980+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-30T01:32:34.980+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 6
[2022-11-30T01:32:34.980+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-30T01:32:35.137+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2022-11-29 00:00:00+00:00
[2022-11-30T01:32:35.142+0000] {standard_task_runner.py:55} INFO - Started process 232 to run task
[2022-11-30T01:32:35.162+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v01', 'create_postgres_table', 'scheduled__2022-11-29T00:00:00+00:00', '--job-id', '127', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmp02uc2iyo']
[2022-11-30T01:32:35.164+0000] {standard_task_runner.py:83} INFO - Job 127: Subtask create_postgres_table
[2022-11-30T01:32:35.671+0000] {task_command.py:376} INFO - Running <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table scheduled__2022-11-29T00:00:00+00:00 [running]> on host 2c9b3e546def
[2022-11-30T01:32:36.099+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Bruno Lima
AIRFLOW_CTX_DAG_ID=dag_with_postgres_operator_v01
AIRFLOW_CTX_TASK_ID=create_postgres_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-29T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-29T00:00:00+00:00
[2022-11-30T01:32:36.180+0000] {base.py:71} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-11-30T01:32:36.192+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 94, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 288, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 115, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "host.docker.internal" to address: Name or service not known

[2022-11-30T01:32:36.217+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v01, task_id=create_postgres_table, execution_date=20221129T000000, start_date=20221130T013234, end_date=20221130T013236
[2022-11-30T01:32:36.274+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 127 for task create_postgres_table (could not translate host name "host.docker.internal" to address: Name or service not known
; 232)
[2022-11-30T01:32:36.324+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-30T01:32:36.355+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-30T01:34:13.758+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table scheduled__2022-11-29T00:00:00+00:00 [queued]>
[2022-11-30T01:34:13.788+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table scheduled__2022-11-29T00:00:00+00:00 [queued]>
[2022-11-30T01:34:13.789+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-30T01:34:13.789+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 6
[2022-11-30T01:34:13.789+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-30T01:34:13.826+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2022-11-29 00:00:00+00:00
[2022-11-30T01:34:13.830+0000] {standard_task_runner.py:55} INFO - Started process 426 to run task
[2022-11-30T01:34:13.833+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v01', 'create_postgres_table', 'scheduled__2022-11-29T00:00:00+00:00', '--job-id', '138', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmptgipiap5']
[2022-11-30T01:34:13.835+0000] {standard_task_runner.py:83} INFO - Job 138: Subtask create_postgres_table
[2022-11-30T01:34:14.033+0000] {task_command.py:376} INFO - Running <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table scheduled__2022-11-29T00:00:00+00:00 [running]> on host 2c9b3e546def
[2022-11-30T01:34:14.151+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Bruno Lima
AIRFLOW_CTX_DAG_ID=dag_with_postgres_operator_v01
AIRFLOW_CTX_TASK_ID=create_postgres_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-29T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-29T00:00:00+00:00
[2022-11-30T01:34:14.165+0000] {base.py:71} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-11-30T01:34:14.169+0000] {sql.py:315} INFO - Running statement: 
            create table if not exists dag_runs(
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            )
        , parameters: None
[2022-11-30T01:34:14.170+0000] {postgres.py:96} INFO - NOTICE:  relation "dag_runs" already exists, skipping

[2022-11-30T01:34:14.183+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v01, task_id=create_postgres_table, execution_date=20221129T000000, start_date=20221130T013413, end_date=20221130T013414
[2022-11-30T01:34:14.217+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-11-30T01:34:14.245+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
