[2022-11-22T01:09:13.063+0000] {processor.py:154} INFO - Started process (PID=402) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:09:13.063+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:09:13.064+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:09:13.064+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:09:13.066+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:09:13.065+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 5, in <module>
    with DAG(
TypeError: __init__() missing 1 required positional argument: 'dag_id'
[2022-11-22T01:09:13.067+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:09:13.085+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.025 seconds
[2022-11-22T01:09:22.122+0000] {processor.py:154} INFO - Started process (PID=416) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:09:22.124+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:09:22.125+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:09:22.125+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:09:22.128+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:09:22.127+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 7
    ) as dag:
    ^
SyntaxError: invalid syntax
[2022-11-22T01:09:22.129+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:09:22.163+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.045 seconds
[2022-11-22T01:09:26.172+0000] {processor.py:154} INFO - Started process (PID=428) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:09:26.172+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:09:26.173+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:09:26.173+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:09:26.204+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:09:26.420+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:09:26.420+0000] {manager.py:507} INFO - Created Permission View: can edit on DAG:our_first_dag
[2022-11-22T01:09:26.432+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:09:26.432+0000] {manager.py:507} INFO - Created Permission View: can delete on DAG:our_first_dag
[2022-11-22T01:09:26.439+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:09:26.439+0000] {manager.py:507} INFO - Created Permission View: can read on DAG:our_first_dag
[2022-11-22T01:09:26.439+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:09:26.439+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:09:26.456+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:09:26.456+0000] {dag.py:2606} INFO - Creating ORM DAG for our_first_dag
[2022-11-22T01:09:26.470+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:09:26.470+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag to None, run_after=None
[2022-11-22T01:09:26.489+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.320 seconds
[2022-11-22T01:09:28.212+0000] {processor.py:154} INFO - Started process (PID=435) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:09:28.213+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:09:28.214+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:09:28.214+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:09:28.227+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:09:28.254+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:09:28.254+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:09:28.286+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:09:28.286+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag to None, run_after=None
[2022-11-22T01:09:28.319+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.109 seconds
[2022-11-22T01:09:42.398+0000] {processor.py:154} INFO - Started process (PID=448) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:09:42.399+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:09:42.399+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:09:42.399+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:09:42.401+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:09:42.400+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 7
    def
      ^
SyntaxError: invalid syntax
[2022-11-22T01:09:42.401+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:09:42.423+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.027 seconds
[2022-11-22T01:09:47.438+0000] {processor.py:154} INFO - Started process (PID=453) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:09:47.439+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:09:47.441+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:09:47.440+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:09:47.445+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:09:47.442+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 7
    descri
    ^
SyntaxError: positional argument follows keyword argument
[2022-11-22T01:09:47.445+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:09:47.477+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.044 seconds
[2022-11-22T01:09:50.520+0000] {processor.py:154} INFO - Started process (PID=467) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:09:50.521+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:09:50.522+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:09:50.522+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:09:50.526+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:09:50.524+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 7
    description
    ^
SyntaxError: positional argument follows keyword argument
[2022-11-22T01:09:50.527+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:09:50.547+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.032 seconds
[2022-11-22T01:10:04.631+0000] {processor.py:154} INFO - Started process (PID=480) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:10:04.632+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:10:04.634+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:10:04.633+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:10:04.645+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:10:04.728+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:10:04.728+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:10:04.758+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:10:04.757+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag to None, run_after=None
[2022-11-22T01:10:04.786+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.158 seconds
[2022-11-22T01:10:11.673+0000] {processor.py:154} INFO - Started process (PID=485) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:10:11.674+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:10:11.674+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:10:11.674+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:10:11.683+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:10:11.710+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:10:11.710+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:10:11.745+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:10:11.745+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag to None, run_after=None
[2022-11-22T01:10:11.767+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.097 seconds
[2022-11-22T01:10:13.696+0000] {processor.py:154} INFO - Started process (PID=499) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:10:13.697+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:10:13.698+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:10:13.698+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:10:13.720+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:10:13.751+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:10:13.750+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:10:13.785+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:10:13.785+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag to None, run_after=None
[2022-11-22T01:10:13.808+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.117 seconds
[2022-11-22T01:10:15.819+0000] {processor.py:154} INFO - Started process (PID=504) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:10:15.820+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:10:15.821+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:10:15.821+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:10:15.843+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:10:15.873+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:10:15.873+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:10:15.903+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:10:15.903+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag to None, run_after=None
[2022-11-22T01:10:15.925+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.110 seconds
[2022-11-22T01:10:23.884+0000] {processor.py:154} INFO - Started process (PID=516) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:10:23.885+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:10:23.885+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:10:23.885+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:10:23.895+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:10:23.923+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:10:23.923+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:10:23.961+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:10:23.960+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag to None, run_after=None
[2022-11-22T01:10:23.987+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.105 seconds
[2022-11-22T01:10:26.994+0000] {processor.py:154} INFO - Started process (PID=523) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:10:26.994+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:10:26.995+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:10:26.995+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:10:27.007+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:10:27.033+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:10:27.032+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:10:27.079+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:10:27.079+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag to None, run_after=None
[2022-11-22T01:10:27.103+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.112 seconds
[2022-11-22T01:10:31.060+0000] {processor.py:154} INFO - Started process (PID=528) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:10:31.067+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:10:31.068+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:10:31.068+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:10:31.072+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:10:31.070+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8
    start_date
    ^
SyntaxError: positional argument follows keyword argument
[2022-11-22T01:10:31.073+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:10:31.104+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.049 seconds
[2022-11-22T01:10:36.089+0000] {processor.py:154} INFO - Started process (PID=542) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:10:36.089+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:10:36.090+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:10:36.090+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:10:36.093+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:10:36.092+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    start_date=datetime
NameError: name 'datetime' is not defined
[2022-11-22T01:10:36.093+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:10:36.113+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.027 seconds
[2022-11-22T01:10:39.113+0000] {processor.py:154} INFO - Started process (PID=547) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:10:39.113+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:10:39.114+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:10:39.114+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:10:39.115+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:10:39.115+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 9
    ) as dag:
    ^
SyntaxError: invalid syntax
[2022-11-22T01:10:39.116+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:10:39.134+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.024 seconds
[2022-11-22T01:10:47.196+0000] {processor.py:154} INFO - Started process (PID=561) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:10:47.205+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:10:47.205+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:10:47.205+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:10:47.207+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:10:47.206+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 11
    ) as dag:
    ^
SyntaxError: invalid syntax
[2022-11-22T01:10:47.208+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:10:47.239+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.046 seconds
[2022-11-22T01:10:52.237+0000] {processor.py:154} INFO - Started process (PID=566) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:10:52.239+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:10:52.240+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:10:52.240+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:10:52.244+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:10:52.243+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 10, in <module>
    start_date=datetime(2022)
TypeError: function missing required argument 'month' (pos 2)
[2022-11-22T01:10:52.245+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:10:52.277+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.045 seconds
[2022-11-22T01:10:54.301+0000] {processor.py:154} INFO - Started process (PID=571) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:10:54.302+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:10:54.303+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:10:54.302+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:10:54.305+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:10:54.304+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 10, in <module>
    start_date=datetime(2022,7)
TypeError: function missing required argument 'day' (pos 3)
[2022-11-22T01:10:54.305+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:10:54.325+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.027 seconds
[2022-11-22T01:10:57.328+0000] {processor.py:154} INFO - Started process (PID=576) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:10:57.328+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:10:57.329+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:10:57.329+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:10:57.339+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:10:57.418+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:10:57.418+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:10:57.445+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:10:57.445+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag to 2022-11-22T00:00:00+00:00, run_after=2022-11-23T00:00:00+00:00
[2022-11-22T01:10:57.469+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.144 seconds
[2022-11-22T01:10:59.373+0000] {processor.py:154} INFO - Started process (PID=589) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:10:59.374+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:10:59.375+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:10:59.374+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:10:59.390+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:10:59.415+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:10:59.415+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:10:59.447+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:10:59.447+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag to 2022-11-22T00:00:00+00:00, run_after=2022-11-23T00:00:00+00:00
[2022-11-22T01:10:59.475+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.106 seconds
[2022-11-22T01:11:01.394+0000] {processor.py:154} INFO - Started process (PID=594) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:11:01.395+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:11:01.396+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:11:01.396+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:11:01.421+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:11:01.451+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:11:01.451+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:11:01.481+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:11:01.481+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag to 2022-11-22T02:00:00+00:00, run_after=2022-11-23T02:00:00+00:00
[2022-11-22T01:11:01.504+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.116 seconds
[2022-11-22T01:11:03.524+0000] {processor.py:154} INFO - Started process (PID=599) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:11:03.525+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:11:03.526+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:11:03.525+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:11:03.537+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:11:03.562+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:11:03.562+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:11:03.592+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:11:03.592+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag to 2022-11-22T02:00:00+00:00, run_after=2022-11-23T02:00:00+00:00
[2022-11-22T01:11:03.614+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.093 seconds
[2022-11-22T01:11:05.558+0000] {processor.py:154} INFO - Started process (PID=604) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:11:05.559+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:11:05.561+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:11:05.560+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:11:05.584+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:11:05.611+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:11:05.610+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:11:05.638+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:11:05.638+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag to 2022-11-22T02:00:00+00:00, run_after=2022-11-23T02:00:00+00:00
[2022-11-22T01:11:05.658+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.106 seconds
[2022-11-22T01:11:07.664+0000] {processor.py:154} INFO - Started process (PID=609) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:11:07.666+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:11:07.667+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:11:07.667+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:11:07.671+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:11:07.669+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 11
    sh
    ^
SyntaxError: positional argument follows keyword argument
[2022-11-22T01:11:07.671+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:11:07.701+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.041 seconds
[2022-11-22T01:11:11.723+0000] {processor.py:154} INFO - Started process (PID=622) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:11:11.724+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:11:11.724+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:11:11.724+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:11:11.726+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:11:11.725+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 11
    sche
    ^
SyntaxError: positional argument follows keyword argument
[2022-11-22T01:11:11.726+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:11:11.742+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.025 seconds
[2022-11-22T01:11:17.793+0000] {processor.py:154} INFO - Started process (PID=627) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:11:17.793+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:11:17.794+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:11:17.794+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:11:17.797+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:11:17.796+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 11, in <module>
    scheduler_interval=''
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-22T01:11:17.797+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:11:17.817+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.029 seconds
[2022-11-22T01:11:18.815+0000] {processor.py:154} INFO - Started process (PID=632) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:11:18.816+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:11:18.817+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:11:18.817+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:11:18.821+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:11:18.820+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 11, in <module>
    scheduler_interval='@'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-22T01:11:18.822+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:11:18.852+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.043 seconds
[2022-11-22T01:11:20.863+0000] {processor.py:154} INFO - Started process (PID=637) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:11:20.863+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:11:20.864+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:11:20.864+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:11:20.866+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:11:20.865+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 11, in <module>
    scheduler_interval='@burno'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-22T01:11:20.866+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:11:20.884+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.024 seconds
[2022-11-22T01:11:34.965+0000] {processor.py:154} INFO - Started process (PID=660) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:11:34.966+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:11:34.967+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:11:34.966+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:11:34.969+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:11:34.968+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 11, in <module>
    scheduler_interval='@'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-22T01:11:34.969+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:11:34.986+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.023 seconds
[2022-11-22T01:11:39.004+0000] {processor.py:154} INFO - Started process (PID=665) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:11:39.005+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:11:39.006+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:11:39.006+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:11:39.008+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:11:39.007+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 11, in <module>
    scheduler_interval='@daily',
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-22T01:11:39.008+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:11:39.037+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.036 seconds
[2022-11-22T01:11:40.043+0000] {processor.py:154} INFO - Started process (PID=670) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:11:40.044+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:11:40.046+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:11:40.045+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:11:40.050+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:11:40.048+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 11, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-22T01:11:40.051+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:11:40.076+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.038 seconds
[2022-11-22T01:11:49.130+0000] {processor.py:154} INFO - Started process (PID=684) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:11:49.131+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:11:49.132+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:11:49.131+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:11:49.134+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:11:49.133+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 5, in <module>
    default_
NameError: name 'default_' is not defined
[2022-11-22T01:11:49.134+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:11:49.152+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.025 seconds
[2022-11-22T01:11:52.159+0000] {processor.py:154} INFO - Started process (PID=689) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:11:52.160+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:11:52.160+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:11:52.160+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:11:52.162+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:11:52.161+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 5
    default_args =
                  ^
SyntaxError: invalid syntax
[2022-11-22T01:11:52.163+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:11:52.181+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.024 seconds
[2022-11-22T01:11:53.195+0000] {processor.py:154} INFO - Started process (PID=694) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:11:53.196+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:11:53.197+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:11:53.197+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:11:53.201+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:11:53.200+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 13, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-22T01:11:53.202+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:11:53.221+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.032 seconds
[2022-11-22T01:12:06.281+0000] {processor.py:154} INFO - Started process (PID=708) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:12:06.282+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:12:06.282+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:12:06.282+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:12:06.285+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:12:06.284+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 13, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-22T01:12:06.285+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:12:06.302+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.027 seconds
[2022-11-22T01:12:08.322+0000] {processor.py:154} INFO - Started process (PID=722) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:12:08.323+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:12:08.323+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:12:08.323+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:12:08.326+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:12:08.325+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 13, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-22T01:12:08.326+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:12:08.350+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.030 seconds
[2022-11-22T01:12:11.356+0000] {processor.py:154} INFO - Started process (PID=727) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:12:11.358+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:12:11.359+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:12:11.359+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:12:11.363+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:12:11.362+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 13, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-22T01:12:11.364+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:12:11.398+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.046 seconds
[2022-11-22T01:12:15.412+0000] {processor.py:154} INFO - Started process (PID=732) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:12:15.414+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:12:15.415+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:12:15.415+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:12:15.420+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:12:15.418+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 13, in <module>
    scheduler_interval='@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2022-11-22T01:12:15.421+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:12:15.453+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.045 seconds
[2022-11-22T01:12:23.509+0000] {processor.py:154} INFO - Started process (PID=746) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:12:23.510+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:12:23.510+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:12:23.510+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:12:23.512+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:12:23.511+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8
    }
    ^
SyntaxError: invalid syntax
[2022-11-22T01:12:23.512+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:12:23.529+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.023 seconds
[2022-11-22T01:12:30.564+0000] {processor.py:154} INFO - Started process (PID=751) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:12:30.565+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:12:30.566+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:12:30.566+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:12:30.570+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:12:30.568+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 9
    }
    ^
SyntaxError: invalid syntax
[2022-11-22T01:12:30.570+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:12:30.590+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.031 seconds
[2022-11-22T01:12:33.609+0000] {processor.py:154} INFO - Started process (PID=765) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:12:33.611+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:12:33.612+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:12:33.612+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:12:33.616+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:12:33.614+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 9
    }
    ^
SyntaxError: invalid syntax
[2022-11-22T01:12:33.617+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:12:33.645+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.041 seconds
[2022-11-22T01:12:35.643+0000] {processor.py:154} INFO - Started process (PID=770) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:12:35.645+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:12:35.646+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:12:35.645+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:12:35.649+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:12:35.648+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 9
    }
    ^
SyntaxError: invalid syntax
[2022-11-22T01:12:35.650+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:12:35.674+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.035 seconds
[2022-11-22T01:12:38.697+0000] {processor.py:154} INFO - Started process (PID=775) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:12:38.698+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:12:38.698+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:12:38.698+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:12:38.701+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:12:38.700+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay': te
NameError: name 'te' is not defined
[2022-11-22T01:12:38.702+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:12:38.722+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.028 seconds
[2022-11-22T01:12:42.735+0000] {processor.py:154} INFO - Started process (PID=790) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:12:42.736+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:12:42.737+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:12:42.737+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:12:42.739+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:12:42.738+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 1, in <module>
    from datetime import datetime, tetime
ImportError: cannot import name 'tetime' from 'datetime' (/usr/local/lib/python3.7/datetime.py)
[2022-11-22T01:12:42.739+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:12:42.756+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.024 seconds
[2022-11-22T01:12:45.788+0000] {processor.py:154} INFO - Started process (PID=795) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:12:45.789+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:12:45.790+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:12:45.790+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:12:45.793+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:12:45.792+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 1
    from datetime import datetime,
                        ^
SyntaxError: trailing comma not allowed without surrounding parentheses
[2022-11-22T01:12:45.794+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:12:45.816+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.033 seconds
[2022-11-22T01:12:49.822+0000] {processor.py:154} INFO - Started process (PID=800) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:12:49.823+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:12:49.824+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:12:49.824+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:12:49.826+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:12:49.825+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay': te
NameError: name 'te' is not defined
[2022-11-22T01:12:49.827+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:12:49.848+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.029 seconds
[2022-11-22T01:12:57.908+0000] {processor.py:154} INFO - Started process (PID=814) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:12:57.909+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:12:57.910+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:12:57.910+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:12:57.914+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:12:57.913+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay': timedelta(minute)
NameError: name 'minute' is not defined
[2022-11-22T01:12:57.915+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:12:57.936+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.034 seconds
[2022-11-22T01:12:59.933+0000] {processor.py:154} INFO - Started process (PID=819) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:12:59.934+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:12:59.935+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:12:59.935+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:12:59.938+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:12:59.937+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8
    'retry_delay': timedelta(minute=)
                                    ^
SyntaxError: invalid syntax
[2022-11-22T01:12:59.939+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:12:59.965+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.037 seconds
[2022-11-22T01:13:01.982+0000] {processor.py:154} INFO - Started process (PID=824) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:13:01.983+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:13:01.983+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:13:01.983+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:13:01.986+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:13:01.985+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay': timedelta(minute=2)
TypeError: 'minute' is an invalid keyword argument for __new__()
[2022-11-22T01:13:01.986+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:13:02.002+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.022 seconds
[2022-11-22T01:13:05.017+0000] {processor.py:154} INFO - Started process (PID=829) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:13:05.018+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:13:05.019+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:13:05.019+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:13:05.023+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:13:05.022+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay': timedelta(minute=2)
TypeError: 'minute' is an invalid keyword argument for __new__()
[2022-11-22T01:13:05.024+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:13:05.045+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.032 seconds
[2022-11-22T01:13:06.058+0000] {processor.py:154} INFO - Started process (PID=843) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:13:06.059+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:13:06.059+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:13:06.059+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:13:06.062+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:13:06.061+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 14
    description='This is our first dag that we write',
              ^
SyntaxError: invalid syntax
[2022-11-22T01:13:06.062+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:13:06.080+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.026 seconds
[2022-11-22T01:13:08.091+0000] {processor.py:154} INFO - Started process (PID=848) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:13:08.092+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:13:08.093+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:13:08.093+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:13:08.097+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:13:08.095+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 14
    description='This is our first dag that we write',
              ^
SyntaxError: invalid syntax
[2022-11-22T01:13:08.097+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:13:08.118+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.033 seconds
[2022-11-22T01:13:15.151+0000] {processor.py:154} INFO - Started process (PID=853) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:13:15.152+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:13:15.153+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:13:15.153+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:13:15.156+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:13:15.155+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay': timedelta(minute=2)
TypeError: 'minute' is an invalid keyword argument for __new__()
[2022-11-22T01:13:15.156+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:13:15.176+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.028 seconds
[2022-11-22T01:13:45.324+0000] {processor.py:154} INFO - Started process (PID=885) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:13:45.326+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:13:45.326+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:13:45.326+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:13:45.328+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:13:45.328+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay': timedelta(minute=2)
TypeError: 'minute' is an invalid keyword argument for __new__()
[2022-11-22T01:13:45.329+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:13:45.358+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.037 seconds
[2022-11-22T01:14:15.522+0000] {processor.py:154} INFO - Started process (PID=917) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:14:15.523+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:14:15.524+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:14:15.523+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:14:15.525+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:14:15.525+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay': timedelta(minute=2)
TypeError: 'minute' is an invalid keyword argument for __new__()
[2022-11-22T01:14:15.526+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:14:15.547+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.030 seconds
[2022-11-22T01:14:45.652+0000] {processor.py:154} INFO - Started process (PID=938) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:14:45.653+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:14:45.654+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:14:45.654+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:14:45.657+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:14:45.656+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay': timedelta(minute=2)
TypeError: 'minute' is an invalid keyword argument for __new__()
[2022-11-22T01:14:45.657+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:14:45.677+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.028 seconds
[2022-11-22T01:15:15.795+0000] {processor.py:154} INFO - Started process (PID=971) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:15:15.796+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:15:15.797+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:15:15.797+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:15:15.799+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:15:15.798+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay': timedelta(minute=2)
TypeError: 'minute' is an invalid keyword argument for __new__()
[2022-11-22T01:15:15.799+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:15:15.815+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.026 seconds
[2022-11-22T01:15:33.888+0000] {processor.py:154} INFO - Started process (PID=985) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:15:33.889+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:15:33.890+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:15:33.890+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:15:33.892+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:15:33.891+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 4
    from
        ^
SyntaxError: invalid syntax
[2022-11-22T01:15:33.892+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:15:33.909+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.026 seconds
[2022-11-22T01:15:45.986+0000] {processor.py:154} INFO - Started process (PID=1000) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:15:45.987+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:15:45.988+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:15:45.988+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:15:45.992+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:15:45.990+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 4
    from airflow.
                ^
SyntaxError: invalid syntax
[2022-11-22T01:15:45.992+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:15:46.016+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.036 seconds
[2022-11-22T01:15:52.022+0000] {processor.py:154} INFO - Started process (PID=1014) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:15:52.023+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:15:52.024+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:15:52.024+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:15:52.026+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:15:52.025+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 4
    from airflow.operator.bash
                              ^
SyntaxError: invalid syntax
[2022-11-22T01:15:52.026+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:15:52.050+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.031 seconds
[2022-11-22T01:15:56.083+0000] {processor.py:154} INFO - Started process (PID=1019) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:15:56.083+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:15:56.084+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:15:56.084+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:15:56.086+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:15:56.086+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 4, in <module>
    from airflow.operator.bash import Bash
ModuleNotFoundError: No module named 'airflow.operator'
[2022-11-22T01:15:56.087+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:15:56.110+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.030 seconds
[2022-11-22T01:15:59.115+0000] {processor.py:154} INFO - Started process (PID=1031) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:15:59.115+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:15:59.116+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:15:59.116+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:15:59.120+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:15:59.119+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 4, in <module>
    from airflow.operator.bash import BashOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2022-11-22T01:15:59.120+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:15:59.147+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.035 seconds
[2022-11-22T01:16:02.166+0000] {processor.py:154} INFO - Started process (PID=1038) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:02.167+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:16:02.168+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:16:02.168+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:02.169+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:16:02.169+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 19
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-22T01:16:02.170+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:02.188+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.025 seconds
[2022-11-22T01:16:14.253+0000] {processor.py:154} INFO - Started process (PID=1052) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:14.253+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:16:14.254+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:16:14.254+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:14.256+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:16:14.256+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 4, in <module>
    from airflow.operator.bash import BashOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2022-11-22T01:16:14.257+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:14.274+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.023 seconds
[2022-11-22T01:16:15.269+0000] {processor.py:154} INFO - Started process (PID=1057) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:15.270+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:16:15.270+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:16:15.270+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:15.272+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:16:15.272+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 4, in <module>
    from airflow.operator.bash import BashOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2022-11-22T01:16:15.273+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:15.289+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.022 seconds
[2022-11-22T01:16:17.316+0000] {processor.py:154} INFO - Started process (PID=1062) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:17.317+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:16:17.318+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:16:17.318+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:17.323+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:16:17.322+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 4, in <module>
    from airflow.operator.bash import BashOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2022-11-22T01:16:17.324+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:17.352+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.041 seconds
[2022-11-22T01:16:20.348+0000] {processor.py:154} INFO - Started process (PID=1067) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:20.349+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:16:20.351+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:16:20.350+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:20.356+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:16:20.355+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 4, in <module>
    from airflow.operator.bash import BashOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2022-11-22T01:16:20.357+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:20.386+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.043 seconds
[2022-11-22T01:16:23.420+0000] {processor.py:154} INFO - Started process (PID=1081) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:23.420+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:16:23.421+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:16:23.421+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:23.424+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:16:23.424+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 4, in <module>
    from airflow.operator.bash import BashOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2022-11-22T01:16:23.425+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:23.443+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.030 seconds
[2022-11-22T01:16:26.458+0000] {processor.py:154} INFO - Started process (PID=1086) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:26.459+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:16:26.460+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:16:26.460+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:26.462+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:16:26.461+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 4, in <module>
    from airflow.operator.bash import BashOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2022-11-22T01:16:26.463+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:26.480+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.027 seconds
[2022-11-22T01:16:28.500+0000] {processor.py:154} INFO - Started process (PID=1091) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:28.501+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:16:28.502+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:16:28.502+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:28.507+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:16:28.506+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 4, in <module>
    from airflow.operator.bash import BashOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2022-11-22T01:16:28.508+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:28.527+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.032 seconds
[2022-11-22T01:16:30.530+0000] {processor.py:154} INFO - Started process (PID=1096) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:30.531+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:16:30.532+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:16:30.532+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:30.535+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:16:30.534+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 21
    ba
    ^
SyntaxError: positional argument follows keyword argument
[2022-11-22T01:16:30.536+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:30.569+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.044 seconds
[2022-11-22T01:16:33.587+0000] {processor.py:154} INFO - Started process (PID=1101) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:33.588+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:16:33.590+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:16:33.590+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:33.595+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:16:33.593+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 21
    bash
    ^
SyntaxError: positional argument follows keyword argument
[2022-11-22T01:16:33.596+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:33.617+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.036 seconds
[2022-11-22T01:16:34.619+0000] {processor.py:154} INFO - Started process (PID=1115) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:34.619+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:16:34.620+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:16:34.620+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:34.622+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:16:34.621+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 21
    bash_co
    ^
SyntaxError: positional argument follows keyword argument
[2022-11-22T01:16:34.622+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:34.652+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.036 seconds
[2022-11-22T01:16:37.662+0000] {processor.py:154} INFO - Started process (PID=1120) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:37.663+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:16:37.664+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:16:37.664+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:37.668+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:16:37.667+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 21
    bash_command
    ^
SyntaxError: positional argument follows keyword argument
[2022-11-22T01:16:37.668+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:37.686+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.029 seconds
[2022-11-22T01:16:38.701+0000] {processor.py:154} INFO - Started process (PID=1125) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:38.702+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:16:38.702+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:16:38.702+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:38.705+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:16:38.704+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 4, in <module>
    from airflow.operator.bash import BashOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2022-11-22T01:16:38.705+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:38.732+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.033 seconds
[2022-11-22T01:16:52.794+0000] {processor.py:154} INFO - Started process (PID=1139) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:52.795+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:16:52.796+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:16:52.796+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:52.800+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:16:52.798+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 4, in <module>
    from airflow.operator.bash import BashOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2022-11-22T01:16:52.800+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:52.817+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.027 seconds
[2022-11-22T01:16:54.824+0000] {processor.py:154} INFO - Started process (PID=1144) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:54.825+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:16:54.825+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:16:54.825+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:54.828+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:16:54.827+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 4, in <module>
    from airflow.operator.bash import BashOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2022-11-22T01:16:54.828+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:54.844+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.023 seconds
[2022-11-22T01:16:58.874+0000] {processor.py:154} INFO - Started process (PID=1158) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:58.875+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:16:58.876+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:16:58.876+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:58.879+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:16:58.878+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 4, in <module>
    from airflow.operator.bash import BashOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2022-11-22T01:16:58.880+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:16:58.897+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.028 seconds
[2022-11-22T01:17:00.897+0000] {processor.py:154} INFO - Started process (PID=1163) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:17:00.898+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:17:00.898+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:17:00.898+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:17:00.901+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:17:00.900+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 4, in <module>
    from airflow.operator.bash import BashOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2022-11-22T01:17:00.901+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:17:00.918+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.024 seconds
[2022-11-22T01:17:03.953+0000] {processor.py:154} INFO - Started process (PID=1168) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:17:03.953+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:17:03.954+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:17:03.954+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:17:03.957+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:17:03.956+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 4, in <module>
    from airflow.operator.bash import BashOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2022-11-22T01:17:03.958+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:17:03.981+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.033 seconds
[2022-11-22T01:17:34.121+0000] {processor.py:154} INFO - Started process (PID=1200) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:17:34.121+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:17:34.122+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:17:34.122+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:17:34.124+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:17:34.123+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 4, in <module>
    from airflow.operator.bash import BashOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2022-11-22T01:17:34.124+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:17:34.144+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.026 seconds
[2022-11-22T01:18:04.300+0000] {processor.py:154} INFO - Started process (PID=1223) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:18:04.301+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:18:04.302+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:18:04.302+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:18:04.306+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:18:04.305+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 4, in <module>
    from airflow.operator.bash import BashOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2022-11-22T01:18:04.307+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:18:04.330+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.035 seconds
[2022-11-22T01:18:34.471+0000] {processor.py:154} INFO - Started process (PID=1255) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:18:34.472+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:18:34.473+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:18:34.473+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:18:34.476+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:18:34.475+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 4, in <module>
    from airflow.operator.bash import BashOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2022-11-22T01:18:34.476+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:18:34.494+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.026 seconds
[2022-11-22T01:19:04.644+0000] {processor.py:154} INFO - Started process (PID=1288) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:19:04.645+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:19:04.646+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:19:04.646+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:19:04.648+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:19:04.647+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 4, in <module>
    from airflow.operator.bash import BashOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2022-11-22T01:19:04.648+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:19:04.677+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.035 seconds
[2022-11-22T01:19:34.833+0000] {processor.py:154} INFO - Started process (PID=1313) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:19:34.835+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:19:34.836+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:19:34.836+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:19:34.840+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:19:34.838+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 4, in <module>
    from airflow.operator.bash import BashOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2022-11-22T01:19:34.840+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:19:34.871+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.042 seconds
[2022-11-22T01:20:04.973+0000] {processor.py:154} INFO - Started process (PID=1344) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:20:04.974+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:20:04.974+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:20:04.974+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:20:04.976+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:20:04.976+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 4, in <module>
    from airflow.operator.bash import BashOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2022-11-22T01:20:04.977+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:20:04.993+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.023 seconds
[2022-11-22T01:20:35.120+0000] {processor.py:154} INFO - Started process (PID=1367) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:20:35.121+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:20:35.122+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:20:35.121+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:20:35.124+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:20:35.123+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 4, in <module>
    from airflow.operator.bash import BashOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2022-11-22T01:20:35.124+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:20:35.142+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.025 seconds
[2022-11-22T01:21:05.259+0000] {processor.py:154} INFO - Started process (PID=1398) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:21:05.259+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:21:05.260+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:21:05.260+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:21:05.262+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:21:05.261+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 4, in <module>
    from airflow.operator.bash import BashOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2022-11-22T01:21:05.263+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:21:05.278+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.023 seconds
[2022-11-22T01:21:35.402+0000] {processor.py:154} INFO - Started process (PID=1431) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:21:35.402+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:21:35.403+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:21:35.403+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:21:35.405+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:21:35.404+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 4, in <module>
    from airflow.operator.bash import BashOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2022-11-22T01:21:35.405+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:21:35.426+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.027 seconds
[2022-11-22T01:23:51.708+0000] {processor.py:154} INFO - Started process (PID=161) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:23:51.710+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:23:51.710+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:23:51.710+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:23:51.714+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:23:51.713+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 4, in <module>
    from airflow.operator.bash import BashOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2022-11-22T01:23:51.714+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:23:51.732+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.026 seconds
[2022-11-22T01:24:21.852+0000] {processor.py:154} INFO - Started process (PID=198) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:24:21.853+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:24:21.853+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:24:21.853+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:24:21.855+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:24:21.854+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 4, in <module>
    from airflow.operator.bash import BashOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2022-11-22T01:24:21.855+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:24:21.872+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.023 seconds
[2022-11-22T01:24:52.022+0000] {processor.py:154} INFO - Started process (PID=220) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:24:52.023+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:24:52.023+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:24:52.023+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:24:52.025+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:24:52.024+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 4, in <module>
    from airflow.operator.bash import BashOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2022-11-22T01:24:52.025+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:24:52.042+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.024 seconds
[2022-11-22T01:25:04.104+0000] {processor.py:154} INFO - Started process (PID=234) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:25:04.105+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:25:04.105+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:25:04.105+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:25:04.107+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:25:04.106+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 4
    from airflow.operators.bash import
                                      ^
SyntaxError: invalid syntax
[2022-11-22T01:25:04.107+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:25:04.126+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.024 seconds
[2022-11-22T01:25:06.136+0000] {processor.py:154} INFO - Started process (PID=248) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:25:06.137+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:25:06.140+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:25:06.140+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:25:06.142+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:25:06.141+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 4
    from airflow.operators.bash import
                                      ^
SyntaxError: invalid syntax
[2022-11-22T01:25:06.142+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:25:06.163+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.029 seconds
[2022-11-22T01:25:11.196+0000] {processor.py:154} INFO - Started process (PID=253) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:25:11.197+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:25:11.198+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:25:11.198+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:25:11.201+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:25:11.200+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 4, in <module>
    from airflow.operator.bash import BashOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2022-11-22T01:25:11.202+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:25:11.324+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.133 seconds
[2022-11-22T01:25:14.237+0000] {processor.py:154} INFO - Started process (PID=258) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:25:14.238+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:25:14.240+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:25:14.239+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:25:14.243+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:25:14.242+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 3
    from airflow.operators.bash import
                                      ^
SyntaxError: invalid syntax
[2022-11-22T01:25:14.244+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:25:14.372+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.140 seconds
[2022-11-22T01:25:19.391+0000] {processor.py:154} INFO - Started process (PID=272) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:25:19.392+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:25:19.393+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:25:19.393+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:25:19.511+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:25:19.510+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 7, in <module>
    'retry_delay': timedelta(minute=2)
TypeError: 'minute' is an invalid keyword argument for __new__()
[2022-11-22T01:25:19.511+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:25:19.530+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.142 seconds
[2022-11-22T01:25:21.683+0000] {processor.py:154} INFO - Started process (PID=277) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:25:21.683+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:25:21.683+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:25:21.683+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:25:21.688+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:25:21.687+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 9, in <module>
    'retry_delay': timedelta(minute=2)
TypeError: 'minute' is an invalid keyword argument for __new__()
[2022-11-22T01:25:21.688+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:25:21.707+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.139 seconds
[2022-11-22T01:25:52.012+0000] {processor.py:154} INFO - Started process (PID=307) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:25:52.013+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:25:52.014+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:25:52.014+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:25:52.021+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:25:52.020+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 9, in <module>
    'retry_delay': timedelta(minute=2)
TypeError: 'minute' is an invalid keyword argument for __new__()
[2022-11-22T01:25:52.022+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:25:52.046+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.037 seconds
[2022-11-22T01:26:17.140+0000] {processor.py:154} INFO - Started process (PID=332) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:26:17.141+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:26:17.141+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:26:17.141+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:26:17.158+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:26:17.250+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:26:17.250+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:26:17.285+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:26:17.284+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag to 2022-11-23T00:00:00+00:00, run_after=2022-11-24T00:00:00+00:00
[2022-11-22T01:26:17.313+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.176 seconds
[2022-11-22T01:26:47.441+0000] {processor.py:154} INFO - Started process (PID=354) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:26:47.442+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:26:47.442+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:26:47.442+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:26:47.458+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:26:47.496+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:26:47.496+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:26:47.527+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:26:47.527+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag to 2022-11-23T00:00:00+00:00, run_after=2022-11-24T00:00:00+00:00
[2022-11-22T01:26:47.547+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.110 seconds
[2022-11-22T01:27:17.670+0000] {processor.py:154} INFO - Started process (PID=384) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:27:17.672+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:27:17.672+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:27:17.672+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:27:17.689+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:27:17.725+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:27:17.725+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:27:17.752+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:27:17.752+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag to 2022-11-23T00:00:00+00:00, run_after=2022-11-24T00:00:00+00:00
[2022-11-22T01:27:17.771+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.104 seconds
[2022-11-22T01:27:47.817+0000] {processor.py:154} INFO - Started process (PID=415) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:27:47.818+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:27:47.818+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:27:47.818+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:27:47.833+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:27:47.871+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:27:47.871+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:27:47.905+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:27:47.904+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag to 2022-11-23T00:00:00+00:00, run_after=2022-11-24T00:00:00+00:00
[2022-11-22T01:27:47.927+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.112 seconds
[2022-11-22T01:28:18.053+0000] {processor.py:154} INFO - Started process (PID=437) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:28:18.054+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:28:18.054+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:28:18.054+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:28:18.071+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:28:18.110+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:28:18.110+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:28:18.144+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:28:18.144+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag to 2022-11-23T00:00:00+00:00, run_after=2022-11-24T00:00:00+00:00
[2022-11-22T01:28:18.167+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.116 seconds
[2022-11-22T01:28:48.209+0000] {processor.py:154} INFO - Started process (PID=470) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:28:48.209+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:28:48.210+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:28:48.210+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:28:48.228+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:28:48.272+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:28:48.271+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:28:48.305+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:28:48.304+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag to 2022-11-23T00:00:00+00:00, run_after=2022-11-24T00:00:00+00:00
[2022-11-22T01:28:48.325+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.119 seconds
[2022-11-22T01:29:18.477+0000] {processor.py:154} INFO - Started process (PID=492) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:29:18.478+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:29:18.478+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:29:18.478+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:29:18.493+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:29:18.529+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:29:18.529+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:29:18.556+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:29:18.556+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag to 2022-11-23T00:00:00+00:00, run_after=2022-11-24T00:00:00+00:00
[2022-11-22T01:29:18.576+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.101 seconds
[2022-11-22T01:29:48.646+0000] {processor.py:154} INFO - Started process (PID=524) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:29:48.647+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:29:48.647+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:29:48.647+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:29:48.663+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:29:48.705+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:29:48.705+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:29:48.739+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:29:48.738+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag to 2022-11-23T00:00:00+00:00, run_after=2022-11-24T00:00:00+00:00
[2022-11-22T01:29:48.760+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.117 seconds
[2022-11-22T01:29:49.730+0000] {processor.py:154} INFO - Started process (PID=529) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:29:49.731+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:29:49.732+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:29:49.732+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:29:49.767+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag_v5']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:29:49.920+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:29:49.919+0000] {manager.py:507} INFO - Created Permission View: can edit on DAG:our_first_dag_v5
[2022-11-22T01:29:49.929+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:29:49.929+0000] {manager.py:507} INFO - Created Permission View: can read on DAG:our_first_dag_v5
[2022-11-22T01:29:49.937+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:29:49.937+0000] {manager.py:507} INFO - Created Permission View: can delete on DAG:our_first_dag_v5
[2022-11-22T01:29:49.938+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:29:49.937+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:29:49.954+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:29:49.954+0000] {dag.py:2606} INFO - Creating ORM DAG for our_first_dag_v5
[2022-11-22T01:29:49.970+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:29:49.970+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag_v5 to 2021-07-30T00:00:00+00:00, run_after=2021-07-31T00:00:00+00:00
[2022-11-22T01:29:49.989+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.265 seconds
[2022-11-22T01:29:51.801+0000] {processor.py:154} INFO - Started process (PID=534) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:29:51.802+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:29:51.803+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:29:51.803+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:29:51.823+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag_v5']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:29:51.849+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:29:51.849+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:29:51.885+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:29:51.885+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag_v5 to 2021-07-30T00:00:00+00:00, run_after=2021-07-31T00:00:00+00:00
[2022-11-22T01:29:51.907+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.108 seconds
[2022-11-22T01:30:09.906+0000] {processor.py:154} INFO - Started process (PID=556) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:30:09.908+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:30:09.909+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:30:09.909+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:30:09.940+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag_v5']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:30:09.969+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:30:09.968+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:30:10.001+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:30:10.001+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag_v5 to 2021-07-30T00:00:00+00:00, run_after=2021-07-31T00:00:00+00:00
[2022-11-22T01:30:10.022+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.121 seconds
[2022-11-22T01:30:11.029+0000] {processor.py:154} INFO - Started process (PID=561) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:30:11.030+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:30:11.031+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:30:11.031+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:30:11.054+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:30:11.093+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:30:11.093+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:30:11.124+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:30:11.124+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag to 2022-11-23T00:00:00+00:00, run_after=2022-11-24T00:00:00+00:00
[2022-11-22T01:30:11.145+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.119 seconds
[2022-11-22T01:30:41.195+0000] {processor.py:154} INFO - Started process (PID=600) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:30:41.196+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:30:41.197+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:30:41.197+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:30:41.212+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:30:41.263+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:30:41.263+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:30:41.291+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:30:41.291+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag to 2022-11-23T00:00:00+00:00, run_after=2022-11-24T00:00:00+00:00
[2022-11-22T01:30:41.313+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.122 seconds
[2022-11-22T01:31:11.441+0000] {processor.py:154} INFO - Started process (PID=632) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:31:11.442+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:31:11.442+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:31:11.442+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:31:11.458+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:31:11.496+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:31:11.496+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:31:11.528+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:31:11.528+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag to 2022-11-23T00:00:00+00:00, run_after=2022-11-24T00:00:00+00:00
[2022-11-22T01:31:11.549+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.110 seconds
[2022-11-22T01:31:41.577+0000] {processor.py:154} INFO - Started process (PID=663) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:31:41.578+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:31:41.578+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:31:41.578+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:31:41.596+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:31:41.636+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:31:41.636+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:31:41.670+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:31:41.670+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag to 2022-11-23T00:00:00+00:00, run_after=2022-11-24T00:00:00+00:00
[2022-11-22T01:31:41.692+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.118 seconds
[2022-11-22T01:32:04.766+0000] {processor.py:154} INFO - Started process (PID=687) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:32:04.767+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:32:04.769+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:32:04.768+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:32:04.801+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:32:04.845+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:32:04.845+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:32:04.887+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:32:04.887+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag to 2022-11-23T00:00:00+00:00, run_after=2022-11-24T00:00:00+00:00
[2022-11-22T01:32:04.928+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.167 seconds
[2022-11-22T01:32:06.820+0000] {processor.py:154} INFO - Started process (PID=692) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:32:06.821+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:32:06.821+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:32:06.821+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:32:06.833+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:32:06.832+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 24, in <module>
    tas
NameError: name 'tas' is not defined
[2022-11-22T01:32:06.833+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:32:06.854+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.037 seconds
[2022-11-22T01:32:09.845+0000] {processor.py:154} INFO - Started process (PID=697) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:32:09.845+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:32:09.846+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:32:09.846+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:32:09.847+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:32:09.847+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 24
    task2 =
           ^
SyntaxError: invalid syntax
[2022-11-22T01:32:09.848+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:32:09.866+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.024 seconds
[2022-11-22T01:32:12.868+0000] {processor.py:154} INFO - Started process (PID=702) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:32:12.869+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:32:12.870+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:32:12.870+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:32:12.904+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:32:12.946+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:32:12.945+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:32:12.981+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:32:12.981+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag to 2022-11-23T00:00:00+00:00, run_after=2022-11-24T00:00:00+00:00
[2022-11-22T01:32:13.003+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.141 seconds
[2022-11-22T01:32:13.916+0000] {processor.py:154} INFO - Started process (PID=709) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:32:13.917+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:32:13.917+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:32:13.917+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:32:13.927+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:32:13.927+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 25, in <module>
    tas
NameError: name 'tas' is not defined
[2022-11-22T01:32:13.928+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:32:13.950+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.037 seconds
[2022-11-22T01:32:19.949+0000] {processor.py:154} INFO - Started process (PID=721) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:32:19.950+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:32:19.951+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:32:19.951+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:32:19.960+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:32:19.959+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 25, in <module>
    task_id=''
TypeError: BaseException() takes no keyword arguments
[2022-11-22T01:32:19.961+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:32:19.981+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.034 seconds
[2022-11-22T01:32:22.010+0000] {processor.py:154} INFO - Started process (PID=726) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:32:22.010+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:32:22.011+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:32:22.011+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:32:22.022+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:32:22.021+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 25, in <module>
    task_id='se'
TypeError: BaseException() takes no keyword arguments
[2022-11-22T01:32:22.023+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:32:22.043+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.035 seconds
[2022-11-22T01:32:52.152+0000] {processor.py:154} INFO - Started process (PID=758) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:32:52.153+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:32:52.154+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:32:52.154+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:32:52.167+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:32:52.166+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 25, in <module>
    task_id='se'
TypeError: BaseException() takes no keyword arguments
[2022-11-22T01:32:52.167+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:32:52.191+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.042 seconds
[2022-11-22T01:33:07.267+0000] {processor.py:154} INFO - Started process (PID=772) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:33:07.268+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:33:07.269+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:33:07.269+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:33:07.302+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:33:07.403+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:33:07.402+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:33:07.436+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:33:07.436+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag to 2022-11-23T00:00:00+00:00, run_after=2022-11-24T00:00:00+00:00
[2022-11-22T01:33:07.460+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.198 seconds
[2022-11-22T01:33:09.296+0000] {processor.py:154} INFO - Started process (PID=777) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:33:09.297+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:33:09.298+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:33:09.298+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:33:09.328+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:33:09.358+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:33:09.358+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:33:09.390+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:33:09.390+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag to 2022-11-23T00:00:00+00:00, run_after=2022-11-24T00:00:00+00:00
[2022-11-22T01:33:09.413+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.122 seconds
[2022-11-22T01:33:10.310+0000] {processor.py:154} INFO - Started process (PID=782) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:33:10.311+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:33:10.311+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:33:10.311+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:33:10.314+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:33:10.312+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 29
    task1.
         ^
SyntaxError: invalid syntax
[2022-11-22T01:33:10.314+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:33:10.334+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.027 seconds
[2022-11-22T01:33:12.327+0000] {processor.py:154} INFO - Started process (PID=796) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:33:12.328+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:33:12.328+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:33:12.328+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:33:12.338+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:33:12.337+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 29, in <module>
    task1.down
AttributeError: 'BashOperator' object has no attribute 'down'
[2022-11-22T01:33:12.338+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:33:12.357+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.034 seconds
[2022-11-22T01:33:28.437+0000] {processor.py:154} INFO - Started process (PID=810) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:33:28.438+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:33:28.439+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:33:28.439+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:33:28.448+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:33:28.448+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 29, in <module>
    task1.set_down
AttributeError: 'BashOperator' object has no attribute 'set_down'
[2022-11-22T01:33:28.449+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:33:28.465+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.030 seconds
[2022-11-22T01:33:32.469+0000] {processor.py:154} INFO - Started process (PID=815) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:33:32.469+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:33:32.470+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:33:32.470+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:33:32.479+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:33:32.478+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 29, in <module>
    task1.set_downstre
AttributeError: 'BashOperator' object has no attribute 'set_downstre'
[2022-11-22T01:33:32.479+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:33:32.496+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.031 seconds
[2022-11-22T01:33:36.527+0000] {processor.py:154} INFO - Started process (PID=830) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:33:36.527+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:33:36.528+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:33:36.528+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:33:36.538+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:33:36.537+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 29, in <module>
    task1.set_downstream()
TypeError: set_downstream() missing 1 required positional argument: 'task_or_task_list'
[2022-11-22T01:33:36.538+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:33:36.554+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.030 seconds
[2022-11-22T01:33:39.569+0000] {processor.py:154} INFO - Started process (PID=835) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:33:39.570+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:33:39.571+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:33:39.571+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:33:39.604+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:33:39.696+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:33:39.695+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:33:39.727+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:33:39.727+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag to 2022-11-23T00:00:00+00:00, run_after=2022-11-24T00:00:00+00:00
[2022-11-22T01:33:39.753+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.188 seconds
[2022-11-22T01:33:44.621+0000] {processor.py:154} INFO - Started process (PID=840) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:33:44.622+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:33:44.623+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:33:44.623+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:33:44.658+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag2']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:33:44.802+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:33:44.802+0000] {manager.py:507} INFO - Created Permission View: can edit on DAG:our_first_dag2
[2022-11-22T01:33:44.811+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:33:44.811+0000] {manager.py:507} INFO - Created Permission View: can read on DAG:our_first_dag2
[2022-11-22T01:33:44.819+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:33:44.818+0000] {manager.py:507} INFO - Created Permission View: can delete on DAG:our_first_dag2
[2022-11-22T01:33:44.819+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:33:44.819+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:33:44.836+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:33:44.835+0000] {dag.py:2606} INFO - Creating ORM DAG for our_first_dag2
[2022-11-22T01:33:44.852+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:33:44.852+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag2 to 2022-11-23T00:00:00+00:00, run_after=2022-11-24T00:00:00+00:00
[2022-11-22T01:33:44.875+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.257 seconds
[2022-11-22T01:34:14.974+0000] {processor.py:154} INFO - Started process (PID=871) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:34:14.975+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:34:14.976+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:34:14.975+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:34:14.991+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag2']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:34:15.029+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:34:15.029+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:34:15.060+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:34:15.060+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag2 to 2022-11-23T00:00:00+00:00, run_after=2022-11-24T00:00:00+00:00
[2022-11-22T01:34:15.083+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.111 seconds
[2022-11-22T01:34:45.207+0000] {processor.py:154} INFO - Started process (PID=903) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:34:45.208+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:34:45.209+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:34:45.209+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:34:45.231+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag2']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:34:45.298+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:34:45.298+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:34:45.343+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:34:45.343+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag2 to 2022-11-23T00:00:00+00:00, run_after=2022-11-24T00:00:00+00:00
[2022-11-22T01:34:45.373+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.172 seconds
[2022-11-22T01:35:15.536+0000] {processor.py:154} INFO - Started process (PID=926) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:35:15.537+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:35:15.538+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:35:15.538+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:35:15.569+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag2']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:35:15.605+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:35:15.604+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:35:15.632+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:35:15.632+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag2 to 2022-11-23T00:00:00+00:00, run_after=2022-11-24T00:00:00+00:00
[2022-11-22T01:35:15.651+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.120 seconds
[2022-11-22T01:35:45.679+0000] {processor.py:154} INFO - Started process (PID=958) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:35:45.680+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:35:45.681+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:35:45.680+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:35:45.697+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag2']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:35:45.736+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:35:45.736+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:35:45.767+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:35:45.767+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag2 to 2022-11-23T00:00:00+00:00, run_after=2022-11-24T00:00:00+00:00
[2022-11-22T01:35:45.787+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.113 seconds
[2022-11-22T01:36:15.958+0000] {processor.py:154} INFO - Started process (PID=981) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:36:15.959+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:36:15.960+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:36:15.959+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:36:15.976+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag2']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:36:16.015+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:36:16.015+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:36:16.045+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:36:16.045+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag2 to 2022-11-23T00:00:00+00:00, run_after=2022-11-24T00:00:00+00:00
[2022-11-22T01:36:16.066+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.110 seconds
[2022-11-22T01:36:46.107+0000] {processor.py:154} INFO - Started process (PID=1011) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:36:46.108+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:36:46.109+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:36:46.108+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:36:46.123+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag2']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:36:46.160+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:36:46.160+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:36:46.188+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:36:46.188+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag2 to 2022-11-23T00:00:00+00:00, run_after=2022-11-24T00:00:00+00:00
[2022-11-22T01:36:46.208+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.103 seconds
[2022-11-22T01:37:16.365+0000] {processor.py:154} INFO - Started process (PID=1044) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:37:16.366+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:37:16.367+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:37:16.366+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:37:16.392+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag2']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:37:16.439+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:37:16.439+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:37:16.474+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:37:16.474+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag2 to 2022-11-23T00:00:00+00:00, run_after=2022-11-24T00:00:00+00:00
[2022-11-22T01:37:16.504+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.141 seconds
[2022-11-22T01:37:26.437+0000] {processor.py:154} INFO - Started process (PID=1049) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:37:26.438+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:37:26.439+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:37:26.439+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:37:26.473+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag_v5']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:37:26.575+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:37:26.575+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:37:26.601+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:37:26.601+0000] {dag.py:2606} INFO - Creating ORM DAG for our_first_dag_v5
[2022-11-22T01:37:26.617+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:37:26.617+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag_v5 to 2021-07-30T00:00:00+00:00, run_after=2021-07-31T00:00:00+00:00
[2022-11-22T01:37:26.646+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.215 seconds
[2022-11-22T01:37:29.611+0000] {processor.py:154} INFO - Started process (PID=1063) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:37:29.612+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:37:29.613+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:37:29.613+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:37:29.637+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag_v5']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:37:29.665+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:37:29.665+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:37:29.698+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:37:29.698+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag_v5 to 2021-07-30T00:00:00+00:00, run_after=2021-07-31T00:00:00+00:00
[2022-11-22T01:37:29.723+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.115 seconds
[2022-11-22T01:37:59.968+0000] {processor.py:154} INFO - Started process (PID=1330) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:37:59.969+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:37:59.971+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:37:59.970+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:38:00.011+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag_v5']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:38:00.159+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:38:00.158+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:38:00.188+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:38:00.188+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag_v5 to 2021-08-27T00:00:00+00:00, run_after=2021-08-28T00:00:00+00:00
[2022-11-22T01:38:00.225+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.259 seconds
[2022-11-22T01:38:30.401+0000] {processor.py:154} INFO - Started process (PID=1582) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:38:30.407+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:38:30.408+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:38:30.408+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:38:30.432+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag_v5']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:38:30.514+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:38:30.513+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:38:30.552+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:38:30.552+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag_v5 to 2021-09-21T00:00:00+00:00, run_after=2021-09-22T00:00:00+00:00
[2022-11-22T01:38:30.575+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.181 seconds
[2022-11-22T01:38:47.565+0000] {processor.py:154} INFO - Started process (PID=1719) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:38:47.565+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:38:47.566+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:38:47.566+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:38:47.701+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag2']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:38:47.844+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:38:47.843+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:38:48.012+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:38:48.012+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag2 to 2022-11-23T00:00:00+00:00, run_after=2022-11-24T00:00:00+00:00
[2022-11-22T01:38:48.176+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.624 seconds
[2022-11-22T01:38:56.883+0000] {processor.py:154} INFO - Started process (PID=1768) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:38:56.883+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:38:56.884+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:38:56.884+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:38:56.901+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag2']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:38:56.942+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:38:56.942+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:38:56.973+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:38:56.973+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag2 to 2022-11-23T00:00:00+00:00, run_after=2022-11-24T00:00:00+00:00
[2022-11-22T01:38:56.996+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.116 seconds
[2022-11-22T01:38:57.899+0000] {processor.py:154} INFO - Started process (PID=1773) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:38:57.900+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:38:57.901+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:38:57.901+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:38:57.937+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag2']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:38:57.981+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:38:57.981+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:38:58.012+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:38:58.012+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag2 to 2022-11-23T00:00:00+00:00, run_after=2022-11-24T00:00:00+00:00
[2022-11-22T01:38:58.036+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.143 seconds
[2022-11-22T01:39:27.169+0000] {processor.py:154} INFO - Started process (PID=1805) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:39:27.170+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:39:27.171+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:39:27.171+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:39:27.186+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag2']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:39:27.263+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:39:27.263+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:39:27.289+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:39:27.289+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag2 to 2022-11-03T00:00:00+00:00, run_after=2022-11-04T00:00:00+00:00
[2022-11-22T01:39:27.309+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.142 seconds
[2022-11-22T01:39:29.223+0000] {processor.py:154} INFO - Started process (PID=1823) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:39:29.224+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:39:29.226+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:39:29.225+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:39:29.263+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag2']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:39:29.300+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:39:29.300+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:39:29.387+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:39:29.387+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag2 to 2022-11-22T00:00:00+00:00, run_after=2022-11-23T00:00:00+00:00
[2022-11-22T01:39:29.471+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.256 seconds
[2022-11-22T01:39:51.706+0000] {processor.py:154} INFO - Started process (PID=1932) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:39:51.707+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:39:51.707+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:39:51.707+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:39:51.743+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag_v5']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:39:51.892+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:39:51.892+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:39:51.960+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.259 seconds
[2022-11-22T01:39:56.730+0000] {processor.py:154} INFO - Started process (PID=1957) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:39:56.731+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:39:56.732+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:39:56.732+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:39:56.763+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag_v5']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:39:56.792+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:39:56.792+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:39:56.847+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.122 seconds
[2022-11-22T01:39:57.877+0000] {processor.py:154} INFO - Started process (PID=1962) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:39:57.878+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:39:57.879+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:39:57.879+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:39:57.881+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:39:57.880+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 18
    start_date=datetime(2022, , 29, 2),
                              ^
SyntaxError: invalid syntax
[2022-11-22T01:39:57.881+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:39:57.905+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.030 seconds
[2022-11-22T01:40:00.907+0000] {processor.py:154} INFO - Started process (PID=1967) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:40:00.908+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:40:00.908+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:40:00.908+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:40:00.931+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag_v5']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:40:00.959+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:40:00.959+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:40:01.018+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.114 seconds
[2022-11-22T01:40:02.973+0000] {processor.py:154} INFO - Started process (PID=1972) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:40:02.974+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:40:02.974+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:40:02.974+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:40:02.992+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag_v5']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:40:03.021+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:40:03.021+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:40:03.097+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.125 seconds
[2022-11-22T01:40:28.187+0000] {processor.py:154} INFO - Started process (PID=1996) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:40:28.188+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:40:28.188+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:40:28.188+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:40:28.205+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag_v5']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:40:28.292+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:40:28.292+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:40:28.308+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:40:28.308+0000] {dag.py:2606} INFO - Creating ORM DAG for our_first_dag_v5
[2022-11-22T01:40:28.323+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:40:28.323+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag_v5 to 2022-11-22T00:00:00+00:00, run_after=2022-11-23T00:00:00+00:00
[2022-11-22T01:40:28.347+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.162 seconds
[2022-11-22T01:40:58.494+0000] {processor.py:154} INFO - Started process (PID=2028) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:40:58.495+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:40:58.496+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:40:58.495+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:40:58.512+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag_v5']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:40:58.554+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:40:58.554+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:40:58.589+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:40:58.588+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag_v5 to 2022-11-22T00:00:00+00:00, run_after=2022-11-23T00:00:00+00:00
[2022-11-22T01:40:58.611+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.120 seconds
[2022-11-22T01:41:28.649+0000] {processor.py:154} INFO - Started process (PID=2060) to work on /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:41:28.650+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2022-11-22T01:41:28.650+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:41:28.650+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:41:28.666+0000] {processor.py:766} INFO - DAG(s) dict_keys(['our_first_dag_v5']) retrieved from /opt/airflow/dags/our_first_dag.py
[2022-11-22T01:41:28.701+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:41:28.701+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-22T01:41:28.729+0000] {logging_mixin.py:137} INFO - [2022-11-22T01:41:28.729+0000] {dag.py:3340} INFO - Setting next_dagrun for our_first_dag_v5 to 2022-11-22T00:00:00+00:00, run_after=2022-11-23T00:00:00+00:00
[2022-11-22T01:41:28.750+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.106 seconds
